### ISSUE TITLE
Repeated Round-End Messages

### ISSUE THREAD

**Issue by 10jared105** [caseif/TTT#20] opened 2015-07-04 20:14 UTC
Hey, awesome plugin.

One bug that happens in my server is that once a round ends and "[TTT] The ___ won in arena ___!" is said in chat, it repeats ever so often in my chat. Even if no one plays that map again for a while, the message will still repeat itself. If multiple maps are played, multiple messages repeat.

Am I missing a required plugin?

**Comment by caseif** [comment] 2015-07-04 23:36
This seems to be similar to an earlier issue. What versions of MGLib and TTT do you have installed?

**Comment by 10jared105** [comment] 2015-07-05 19:15
My versions are:

MGLib: v0.4.2
TTT: v0.7.2

**Comment by caseif** [comment] 2015-07-05 20:39
What is the full output of the `/version` command?

**Comment by 10jared105** [comment] 2015-07-05 23:29
[TTT] This server is using TTT version 0.7.2 by Maxim Roncacé

**Comment by 10jared105** [comment] 2015-07-05 23:30
Or did you mean:
[16:29:41 INFO]: This server is running CraftBukkit version git-Spigot-044d928-e8c6403 (MC: 1.8.6) (Implementing API version 1.8.6-R0.1-SNAPSHOT)
[16:29:41 INFO]: Checking version, please wait...
[16:29:43 INFO]: You are 27 version(s) behind

**Comment by 10jared105** [comment] 2015-07-05 23:35
Just updated to the newest version, haha. I'll tell you if it continues, testing now.

**Comment by 10jared105** [comment] 2015-07-06 01:03
Looks fixed! Haha thanks

**Comment by caseif** [comment] 2015-07-06 04:07
Reopening until I can figure out how to compile that version of Spigot and find the cause. Does the issue still occur if you downgrade back to the version you were on previously?

**Comment by caseif** [comment] 2015-07-07 00:57
I'm unable to reproduce this personally.

**Comment by 10jared105** [comment] 2015-07-07 02:12
Sorry, I'll test this ASAP

**Comment by kebokyo** [comment] 2015-07-09 13:16
Oh right, I forgot this was the MC version of TTT. I saw the CraftBukkit post and I was like "Huh?" :-P

**Comment by caseif** [comment] 2015-07-12 20:44
Any word?

**Comment by caseif** [comment] 2015-07-19 21:29
Closing this for now.

**Closed as completed by caseif** 2015-07-19 21:29 UTC
Labels: bug
