### ISSUE TITLE
Dedicated Mode Errors

### ISSUE THREAD

**Issue by BiGUNMAN** [caseif/TTT#51] opened 2016-08-05 20:18 UTC
## Important

I've put the plugin in dedicated mode and these errors happen when players join: http://pastebin.com/Vb4P1x6N (it seems the plugin doesn't operate properly in the mode).
## TTT Version

0.10.0
## Steel Version

1.2.7
## Full output of `/version` command

PaperSpigot 1.10.2 
## Does the issue occur consistently?

Yes/No

**Comment by caseif** [comment] 2016-08-05 21:09
Thanks for the report, I'll investigate this ASAP. I'm assuming restarting the server has no effect?

**Comment by BiGUNMAN** [comment] 2016-08-05 21:48
None at all, same stuff.

**Comment by caseif** [comment] 2016-08-27 22:06
Resolved via [Rosetta v1.1.2](https://github.com/caseif/Rosetta/releases/tag/v1.1.2). See the release page for a more detailed description of the cause. I'll close this issue once I release a hotfix for TTT.

**Closed as completed** 2016-08-27 22:50 UTC
Labels: bug
