### ISSUE TITLE
Void Problems

### ISSUE THREAD

**Issue by BiGUNMAN** [caseif/TTT#50] opened 2016-07-18 02:32 UTC
## TTT Version

0.10.0
## Steel Version

1.2.7
## Full output of `/version` command

Paper 816
## Description of issue

When players fall into the void they don't die. They keep on teleporting above the 0 position: https://i.gyazo.com/44b891aa999ef223d1f3001e58fca363.gif - (this happens even when game isn't in prepare mode). 
## Steps to replicate issue

Jump off of a map that has a void.
## Does the issue occur consistently?

Yes
## Console Errors?

None

**Comment by caseif** [comment] 2016-07-18 03:22
Seems to be a regression of an earlier bug. This will probably slip to 0.11 but I'll consider releasing a hotfix for it sooner than that.

**Comment by caseif** [comment] 2016-08-27 23:24
Resolved via [Steel v1.2.8](https://github.com/caseif/Steel/releases/tag/v1.2.8).

**Closed as completed** 2016-08-27 23:27 UTC
Labels: bug

**Comment by BiGUNMAN** [comment] 2016-08-28 21:23
Will upload the new versions and see how it fairs.
