### ISSUE TITLE
BUG /ttt carena

### ISSUE THREAD

**Issue by MCG-server** [caseif/TTT#42] opened 2016-04-19 01:21 UTC
hello, I state that I tried (unsuccessfully) in version 0.9.6 up to 0.9.2 but there is a bug !!! ie do "/ ttt hull" but when I get to the point that I have to set the spawn with "ok" does not tell me nothing and does nothing. Could you help me ??
P.S a log directory does not believe that to be no problem ... I also installed steel (version 1.2.0 but still works)

**Comment by caseif** [comment] 2016-04-19 01:22
Are there any config errors? Are you perhaps using a chat-modifying plugin that changes text colors?

**Comment by MCG-server** [comment] 2016-04-19 01:22
no

**Comment by caseif** [comment] 2016-04-19 01:23
To both?

**Comment by MCG-server** [comment] 2016-04-19 01:23
yes, I removed all plugins except ttt and steel
if you want you can try it in person

**Comment by MCG-server** [comment] 2016-04-19 01:25
I hope you can give me a hand because I'd like to bring this minigame in Italy

**Comment by MCG-server** [comment] 2016-04-19 01:25
if you want to step all logs

**Comment by caseif** [comment] 2016-04-19 01:26
Hm... Is your Minecraft client set to the Italian locale? If so, try setting it to English (US) temporarily to see if the bug persists.

**Comment by MCG-server** [comment] 2016-04-19 01:27
Which is?

**Comment by caseif** [comment] 2016-04-19 01:27
Hm?

**Comment by MCG-server** [comment] 2016-04-19 01:28
how can I see if the minecraft client is set to Italian

**Comment by caseif** [comment] 2016-04-19 01:29
Does the interface appear in Italian or in English?

**Comment by MCG-server** [comment] 2016-04-19 01:29
I get it! if I set the Italian language

**Comment by caseif** [comment] 2016-04-19 01:30
Was it set to Italian when the experienced the bug?

**Comment by MCG-server** [comment] 2016-04-19 01:31
I will set the Italian language

and that's why I see the chat translated reeds in config if the place was English?
could this be the cause ??

**Comment by caseif** [comment] 2016-04-19 01:31
I'm not sure yet. When you first experienced the bug, though, was your client set to Italian or to English?

**Comment by MCG-server** [comment] 2016-04-19 01:32
italian
there have always in Italian. He wants to do a test in English?

**Comment by caseif** [comment] 2016-04-19 01:33
Yes, try setting it to English and creating an arena to see if the bug still occurs.

**Comment by MCG-server** [comment] 2016-04-19 01:34
another thing (to be sure) you can pass the download link of ttt and steel to 1.8 ??

**Comment by caseif** [comment] 2016-04-19 01:35
The latest version of TTT is [here](https://github.com/caseif/TTT/releases/tag/v0.9.6), and the latest version of Steel is [here](https://github.com/caseif/Steel/releases/tag/v1.2.1).

**Comment by MCG-server** [comment] 2016-04-19 01:36
but then the version 1.9 is good for 1.8 (ttt and steel) ??

**Comment by caseif** [comment] 2016-04-19 01:36
It will work with 1.7.8 through 1.9.2.

**Comment by MCG-server** [comment] 2016-04-19 01:38
that is if I download version 1.9 and I'm with the 1.8 server will not be problems?

excuse but google translator is not very good

**Comment by caseif** [comment] 2016-04-19 01:39
Yes, both versions I linked will work with 1.8.

**Comment by MCG-server** [comment] 2016-04-19 01:40
ok, I am trying again if there is a bug

**Comment by MCG-server** [comment] 2016-04-19 01:41
I was surprised that responded so fast!
what time is it?

**Comment by caseif** [comment] 2016-04-19 01:41
I'm in the eastern US, so not too late.

**Comment by MCG-server** [comment] 2016-04-19 01:42
in Italy are the 4 am

**Comment by MCG-server** [comment] 2016-04-19 01:44
the bug still persists

**Comment by MCG-server** [comment] 2016-04-19 01:45
if you want you can enter the server and try you in person ... or you step all logs

**Comment by caseif** [comment] 2016-04-19 01:45
Hm. Would you mind installing [the latest dev build](https://ci.caseif.net/job/TTT/branch/develop/156/artifact/build/libs/TTT-0.10.0-SNAPSHOT.jar) to see if the issue persists?

**Comment by MCG-server** [comment] 2016-04-19 01:47
I try it once, always in English?

**Comment by caseif** [comment] 2016-04-19 01:47
Yes. If English works, try Italian too.

**Comment by MCG-server** [comment] 2016-04-19 01:49
I hope that it works and that there are no other bugs

**Comment by MCG-server** [comment] 2016-04-19 01:52
does not work :(, I noticed (i forgot to tell you) wrong needless / ttt import

**Comment by caseif** [comment] 2016-04-19 01:52
What about the import command?

**Comment by MCG-server** [comment] 2016-04-19 01:54
but it might not be the problem that I use paperspigot 1.8 ??

He says "an internal error occurred while Attempting to perform this command"

**Comment by caseif** [comment] 2016-04-19 01:55
Can you upload the error log?

**Comment by MCG-server** [comment] 2016-04-19 01:56
yes,
I noticed that if I do "ok" off the limit (region) tells me that I have to do within the limit (region)

**Comment by MCG-server** [comment] 2016-04-19 01:56
all logs?

**Comment by caseif** [comment] 2016-04-19 01:59
Yes, please upload them to Pastebin or a similar site.

**Comment by MCG-server** [comment] 2016-04-19 02:00
Click the link and you download them
http://download945.mediafire.com/6aq8oyna0p1g/5vkyg6hgdcgybby/logs.rar

**Comment by MCG-server** [comment] 2016-04-19 02:01
I wait for an answer, (I warn you I will when I have to turn off your PC)

**Comment by caseif** [comment] 2016-04-19 02:02
Have you fully restarted (not reloaded) the server recently? (Also, I suggest you update to Java 8 if possible to avoid those key errors you're getting.)

**Comment by MCG-server** [comment] 2016-04-19 02:05
I restart the server every time I put a plugin (I stop and then start), upgrade to Java 8 on my PC or server ???

**Comment by MCG-server** [comment] 2016-04-19 02:07
if I have to update the java server 8 (say 8 for java centos and still buggy) I can not but if I have to upgrade my pc to java already 8 l .... I made such fundamental errors that I get ?? .. I'm not very good at reading logs

**Comment by caseif** [comment] 2016-04-19 02:09
Hm... I think it might actually be a PaperSpigot incompatibility. I'm going to have to look further into this tomorrow.

As far as upgrading to Java 8, you should upgrade your PC just for security reasons (Java 7 is no longer supported). If you can't upgrade your server it's no big deal, but some of the errors you're getting aside from the one you originally reported appear to be caused by an outdated key store (Java 8 would fix this).

**Comment by MCG-server** [comment] 2016-04-19 02:15
then tomorrow you will have solved the problem? You could spend the direct link to download the latest version of Java 8

**Comment by caseif** [comment] 2016-04-19 02:17
I'm not sure, it could take longer but I'll strive to have it resolved before the release of 0.10 this weekend. Java 8 is available from https://java.com.

**Comment by MCG-server** [comment] 2016-04-19 02:18
thanks a lot for everything !!! so far you're the only pluginner that you helped me

**Comment by caseif** [comment] 2016-04-19 02:19
My pleasure.

**Comment by MCG-server** [comment] 2016-04-19 02:19
good night!  my name is still francis in italian francesco

**Comment by MCG-server** [comment] 2016-04-19 13:51
hi!

**Comment by MCG-server** [comment] 2016-04-19 13:53
I feel he put the last of fitting version 1.8 and see if There's Still That bug

**Comment by MCG-server** [comment] 2016-04-19 14:46
I have changed " ok " with "spawn " but no , ( I also tried other versions , but it did not work ) , it's not that maybe in the passage of the " ok " and the next you forgot ( or is buggy ) to put something??
ps but is not it better if you put that if they have to build them ( with world edit) as many minigames ( thus reduce the bugs ) or if not toglio it the " ok " and you invent another thing .... for example when you do / ttt hull gives you the objects in the inventory that are used to create the playing area / a wild sort of menu)

**Comment by caseif** [comment] 2016-04-19 17:02
I'm already aware of what's causing the glitch, I just need to figure out why. I'll get back to you when I'm free later tonight.

**Comment by caseif** [comment] 2016-04-19 18:45
Can you shoot me an email at me@caseif.net?

**Comment by MCG-server** [comment] 2016-04-19 18:49
ok

**Comment by MCG-server** [comment] 2016-04-19 18:50
But what should I use ??
gmail or yahoo

**Comment by MCG-server** [comment] 2016-04-19 19:06
I Posted the email

**Comment by MCG-server** [comment] 2016-04-20 00:09
that thing you sent me gives me an error ... yahoo moment at which I sent you the email

**Comment by caseif** [comment] 2016-04-20 14:16
Closing - error was caused by a broken server environment.

**Closed as completed by caseif** 2016-04-20 14:16 UTC
Labels: bug, invalid
