### ISSUE TITLE
Chest didn't dissapear

### ISSUE THREAD

**Issue by VincentVerdynanta** [caseif/TTT#34] opened 2015-11-22 15:05 UTC
First image is when it's ROUND OVER (as you can see on the sidebar)
![2015-11-22_22 02 09](https://cloud.githubusercontent.com/assets/2397514/11324453/c45d85a8-9164-11e5-8d37-a10046d25ea2.png)

Second image is after match, the chest doesn't dissapear from the map
![2015-11-22_22 02 30](https://cloud.githubusercontent.com/assets/2397514/11324454/c4613158-9164-11e5-8a87-7e1ca5558d0c.png)

**Comment by caseif** [comment] 2015-11-22 16:41
I'm unable to reproduce this on my end. A few questions:
1. Does this happen consistently? (i.e. Does every body fail to disappear when the round ends?)
2. Which round stage did the player die in?
3. Were any error printed to the console by TTT?

**Comment by ghost** [comment] 2015-11-23 04:00
1) @caseif Yeah All the Rounds. This is a Bug. In the Lastest Version 0.9.0
2) All The Rounds?
3) I see No Error logs in my console by TTT, Maybe Bugs in Coding

I Just Tested It Just Now In My Server.

**Comment by caseif** [comment] 2015-11-23 04:01
Could you post the output of the `/plugins` command, or, if you prefer, email it to me?

**Comment by ghost** [comment] 2015-11-23 04:01
well i have Tons Of Plugins

**Comment by caseif** [comment] 2015-11-23 04:02
Understood, but right now I don't have any leads on what's causing this behavior so I may be able to identify a conflict from the listing.

**Comment by ghost** [comment] 2015-11-23 04:03
[12:02:21] [Client thread/INFO]: [CHAT] Plugins (97): Downloader, EnchantSign, BarAPI, PlugMan, Smeltery, AutoLapis, LuckyBlock, Autocast, CheckPoints, icJukeBox, PotionStacker, TitleManager, SpawnTP, HomingArrow, MultiMOTD, LaggRemover, ProtocolLib, ResourcePackApi, Steel, ErnixJoinMessage, GroupManager, PluginsDownloader, SkinsRestorer, ScheduledCommands, VoxelSniper, MoreHearts, SuperCubeBros, CoreProtect, Excavator, dynmap, CustomTab, WorldEdit, MultiTexture, TimTheEnchanter, Essentials, PacketListenerApi, ClearLag, CrackShot, TTT, Votifier, iDisguise, SuperVanish, Vault, MassiveCore, EasyListener, EnjinMinecraftPlugin, MinigamesLib, EpicRename, ChestCommands, PlayerVaults, MyCommand, Banknotes, Citizens, EssentialsChat, Checkpoint, FakeAdmin, WorldGuard, Skins, Blacksmith, Denizen, jPanel, PlotMe, AcidIsland, CraftBook, UltraTrader, DynmapPlotMe, CustomEnchantments, Alchemist, CompatNoCheatPlus, SilkSpawners, WGCustomFlags, Builder, ChestShop, PlotMe-DefaultGenerator, NoCheatPlus, OreRegenerator, ServerSigns, Multiverse-Core, Shopkeepers, MobArena, MobHealth, Multiverse-Inventories, MyPet, WarpPortals, AuthMe, HolographicDisplays, EpicSpleef, PhatLoots, MultiWorldMoney, uSkyBlock, MyPet-NPC, Factions, Autorank, CS-CoreLib, TouchscreenHolograms, QuestWorld, Sentry

**Comment by caseif** [comment] 2015-11-23 04:03
Thanks. I'm quite tired atm, but I'll take a look tomorrow to see if I can reproduce this. :)

**Comment by Junhaochia** [comment] 2015-11-23 04:04
ok

**Comment by ghost** [comment] 2015-11-23 04:14
I can make a Video to Reproduce What happens if u want

**Comment by caseif** [comment] 2015-11-23 04:15
I think I understand the issue well enough. I'll take steps tomorrow to try to reproduce it and get back to you if I'm not able to.

**Comment by Junhaochia** [comment] 2015-11-23 04:27
@caseif Corrections* its happens every 2 rounds

**Comment by caseif** [comment] 2015-11-23 14:59
@Junhaochia I'm still not able to reproduce it in a local environment. Could I take you up on that video offer?

**Comment by Junhaochia** [comment] 2015-11-24 11:17
well. let me host a server with steel and ttt only.i try

**Comment by Junhaochia** [comment] 2015-11-24 11:24
@caseif I know What Happen!

**Comment by Junhaochia** [comment] 2015-11-24 11:26
@caseif  what version Are you using?

**Comment by ghost** [comment] 2015-11-24 11:59
@caseif  Werid in the New Server, I'm not able to reproduce the problem again.

**Comment by Junhaochia** [comment] 2015-11-24 12:06
@caseif  I think Maybe theres A Error For Upgrading V0.8.0 To V.0.9.0 , So I Think The Way to Fix this is To Delete Your Old Arena (Which is Created When TTTV0.8.0) and Recreate It (In TTTV0.9.0)

**Comment by ghost** [comment] 2015-11-24 12:29
I tried Deleting Both TTT and Steel , Folder and Jar. Still this Happens
Btw my Server Version: CraftBukkit version git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by caseif** [comment] 2015-11-24 15:43
You're still unable to reproduce it?

**Comment by caseif** [comment] 2015-11-24 15:58
I've managed to replicate it. I'll need some time to further investigate it, though.

**Comment by ghost** [comment] 2015-11-24 16:20
for new server = no , for my dark empire craft server = yes

**Comment by caseif** [comment] 2015-11-24 16:36
Fixed via [`41ff3f3`](https://github.com/caseif/TTT/commit/41ff3f3bf83e2edd84858a028f3f698844fd8987).

**Closed as completed by caseif** 2015-11-24 16:36 UTC
Labels: bug

**Comment by ghost** [comment] 2015-11-24 18:09
Your fast xD

**Comment by ghost** [comment] 2015-11-24 18:10
Tats I was correct about the rollback settings xD lol lucky Guess

**Comment by caseif** [comment] 2015-11-24 18:12
The issue was that the position of the player was being marked for rollback rather than the position of the chest itself. Sometimes a coordinate would be off by a fraction of a meter and be rounded down to the wrong position.
