### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by exzolink** [caseif/TTT#61] opened 2016-09-29 13:23 UTC
Idea: Can you add ability to configure inventory and dmg of every role?

**Comment by Junhaochia** [comment] 2016-10-01 11:40
its possible. But it could take him sometime lol

**Comment by caseif** [comment] 2016-10-01 17:04
Eventually, probably.

**Comment by caseif** [comment] 2016-10-27 05:10
Whoops, just noticed this is a duplicate of #10.

**Closed as completed by caseif** 2016-10-27 05:10 UTC
Labels: duplicate, enhancement
